name: ci

permissions:
  contents: read

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:

  mpich-42:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      mpiname: mpich
      version:

  mpich-41:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      mpiname: mpich
      version: 4.1.3

  mpich-34:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      mpiname: mpich
      version: 3.4.3

  openmpi-50:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      mpiname: openmpi
      version:

  openmpi-41:
    uses: ./.github/workflows/cd-wheel.yml
    with:
      mpiname: openmpi
      version: 4.1.7
